queue_rules:
  - name: default
    conditions:
      - -draft # not a draft
      - base=main

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=renovate[bot]
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: squash
        update_method: rebase
  - name: automatic merge for main when labelled ready to merge
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: squash
        update_method: rebase
