name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: write
  pull-requests: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '24.19.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Clear auth token for OIDC
        run: echo "NODE_AUTH_TOKEN=" >> $GITHUB_ENV

      - name: Upgrade npm for OIDC
        run: npm install -g npm@latest
      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Configure npm registry
        run: npm config set registry https://registry.npmjs.org/
      - name: Create Release Pull Request or Publish
        uses: changesets/action@v2.1.1
        with:
          publish-script: bun run release
          version-script: bun run version-packages
          commit-message: "chore(release): version packages"
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          HUSKY: 0
